### ISSUE TITLE
RFE: detect RUSTC_BOOTSTRAP

### ISSUE THREAD

**Issue by cuviper** [dtolnay/select-rustc#2]
Since `#[rustc::nightly]` includes `dev` builds, it sort of encompasses the situations where it's possible to use unstable features. How would you feel about checking the `RUSTC_BOOTSTRAP` environment variable in that set? Or perhaps that should be a distinct grouping, something like `#[rustc::unstable]`?

**Comment by dtolnay** [comment]
I would prefer not to get involved with RUSTC_BOOTSTRAP unless it would specifically help with bootstrapping rustc. I am not familiar with how the bootstrap currently works but I imagine it has alternative ways to accomplish enabling features -- for example [here in the libc crate](https://github.com/rust-lang/libc/blob/0.2.54/src/lib.rs#L19-L23).

**Comment by cuviper** [comment]
Ok, that's understandable. I have sometimes cheated with `RUSTC_BOOTSTRAP` in private projects just to get `#[bench]` with a stable compiler, but I know that's not really kosher.
